"""Generate funny names by randomly combining names from 2 separate lists."""

import sys
import random

def main():
    """shinchan and his families funny name generator."""
    print("Welcome to the Shinchan and his families funny name generator!")
    print("The names are generated by randomly combining names from 2 separate lists.")

    # List of names

    first_names = ('Naughty Shinchan',
             'Sleepy Hiroshi',   
             'Angry Misae',       
             'Crybaby Masao',     
             'Bossy Nene',         
             'Smarty Kazama',      
             'Fluffy Shiro',       
             'Little Himawari',    
             'Serious Kazama',     
             'Cheerful Shin',      
             'Clumsy Masao',       
             'Gentle Shiro',       
             'Dramatic Nene',      
             'Lazy Hiroshi',       
             'Curious Himawari')
    
    last_names = ('of Kasukabe',          
            'the Nohara',          
            'from Sunflower',      
            'the Action Mask',     
            'the Snack Lover',     
            'of Honeyroad',      
            'the Dog Walker',      
            'of Spring',           
            'the Crayon Artist',   
            'the Nap Champion',    
            'of Futaba',           
            'the Elephant Dancer', 
            'the Pennant Keeper',  
            'of Neighborhood')
    
    while True:
        first_name = random.choice(first_names)
        last_name = random.choice(last_names)

        print("\n\n")
        print("✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼\n")
        print(f"{first_name} {last_name} ")
        print("\n✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼✌🏼")
        print("\n\n")

        try_again = input("Try again? (Press Enter else n to quit) ")

        if try_again.lower() == "n":
            break

    input("Press Enter to exit.")

if __name__ == "__main__":
    main()



        